### ISSUE TITLE
warning linker unused DT entries

### ISSUE THREAD

**Issue by Nono36** [qpython-android/qpython.org#107]
I get some:
'WARNING: linker: [lib]: unused DT entry'
for:
libreadline.so.6 -> when I'm starting the console
zlib.cpython-32m.so -> when running the hello world program

On Android 5.1.1 on Sony Xperia z3 compact

**Comment by cyberwetware** [comment]
It is harmless, ignore it.

**Comment by giuliolunati** [comment]
See https://github.com/kost/android-elf-cleaner

**Comment by riverfor** [comment]
It works, Thank you @giuliolunati 
We will publish a new QPython3 version recently

**Comment by giuliolunati** [comment]
Warning: binaries cleaned this way don't work in Android >= 6

**Comment by riverfor** [comment]
Yes, I found that issue already, do you have other suggestion ?

**Comment by giuliolunati** [comment]
No, it seems to be an irreducible incompatibility:
Android 5.1 complains about that DT entries, while Android >= 6.0 requires
they.
We are facing the same issue in github.com/kbox4

Il 12/lug/2017 06:00, "River" <notifications@github.com> ha scritto:
