### ISSUE TITLE
I want to install QPython without Google Play Store

### ISSUE THREAD

**Issue by gsw945** [qpython-android/qpython.org#116]
So far, I know the only one way to install QPython is installing from the Google Play Store.I wish you can put QPython APK on your server or other storage space, and publish its download address, so that we can install directly without Google Play Store, because my Nokia N1 hasn't Google Play Store that I can't install QPython.

**Comment by steel101** [comment]
https://drive.google.com/folderview?id=0B9zYQXod22uMNGFKdFhwTjgzMnc

Both the new versions are there qpython and qpython3 both updated from playstore

**Comment by riverfor** [comment]
You can get qpython from https://github.com/qpython-android/qpython/releases

and get qpython3 from https://github.com/qpython-android/qpython3/releases
