### ISSUE TITLE
On Android 5.0+ pip install not working

### ISSUE THREAD

**Issue by AkechiShiro** [qpython-android/qpython.org#119]
When entering the command python -m pip install it return error only position independent executable are supported (PIE) it's because of the new security in Android 5.0(i'm sure of it I tested it on android 4.3 and it worked flawlessly) to reallocate or change any memory address of any executables but a lot of apps before didn't support it.
Here is what PIE is :

> Position Independent Executable or PIE allows a program to be relocated, just like a shared object. At each run of the program, the program can be loaded at different addresses to make it harder for an attacker to guess certain program state. 
> ![screenshot_2016-02-18-07-40-28_com hipipal qpy3](https://cloud.githubusercontent.com/assets/14914796/13135683/59a61b32-d613-11e5-83b1-01c23ca85bc1.png)

**Comment by AkechiShiro** [comment]
Working but only on Qpython3 with this command 'python-android5' and 'python-android5 -m pip install "package_you_want" ' and on Qpython only python-android5 work, pip install does not work.

**Comment by riverfor** [comment]
Thanks for feedback, 

On QPython, you can try python-android5 /sdcard/com.hipipal.qpyplus/script/pip_console.py install "package_you_want" ?

BTW: It's strange that the QPython3 didn't recognize your android version automatically. What's the model of your android device ?

**Comment by AkechiShiro** [comment]
My model is a Xiaomi Redmi note 2, and my rom is the lastest officiel one from Miu
Oh and the path is scripts, alright it works, it give me a pip console then i can install any packages from that console.
Here is a screenshot
![screenshot_2016-03-12-15-21-26_com hipipal qpyplus 1](https://cloud.githubusercontent.com/assets/14914796/13723462/9667f35a-e866-11e5-8977-1848984da46d.png)

**Comment by pawatzaza** [comment]
no can speek  eng

**Comment by AkechiShiro** [comment]
Closing this issue since I don't own the device anymore.
