### ISSUE TITLE
import jnius don't work

### ISSUE THREAD

**Issue by FTeinz** [qpython-android/qpython.org#129]
Hello.
I try to import jnius autoclass from my script. but getting following error.

`/data/data/com.hipipal.qpyplus/files/bin/qpython-android5.sh && exit
files/bin/qpython-android5.sh && exit          <
Python 2.7.2 (default, Nov  2 2015, 01:07:37)
[GCC 4.9 20140827 (prerelease)] on linux4
Type "help", "copyright", "credits" or "license" for more information.

> > > from jnius import autoclass
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/QPython/QPython2-core/build/python-install/lib/python2.7/site-packages/jnius/**init**.py", line 13, in <module>
> > >   File "/QPython/QPython2-core/build/python-install/lib/python2.7/site-packages/jnius/reflect.py", line 9, in <module>
> > >   File "jnius_export_class.pxi", line 44, in jnius.jnius.MetaJavaClass.**new** (jnius/jnius.c:13255)
> > > SystemError: NULL result without error in PyObject_Call
> > > `

Do I have to use the Kivy included junius?

Thanks a lot

**Comment by ctmalan** [comment]
Posted the same issue on stackoverflow just now.  Is this a four-month old bug?

**Comment by onekoech** [comment]
I face similar problem

**Comment by riverfor** [comment]
pls insert "#qpy:kivy" to let it run with kivy mode.
