### ISSUE TITLE
要如何更新python3.2到python3.5.1(How I get the python3.2 core upgrade to python3.5.1?)

### ISSUE THREAD

**Issue by mgslong** [qpython-android/qpython.org#134]
How I get the python3.2 core upgrade to python3.5.1?

**Comment by chaihahaha** [comment]
同问I have the same question, please help

**Comment by riverfor** [comment]
Clone the https://github.com/qpython-android/qpython3-core and migrate it from current version to  python3.5.1. (Lots of work to do ).

After that please tell me, I can help with build a new qpython3 with python 3.5.1.
