### ISSUE TITLE
Qpython libraries returning error

### ISSUE THREAD

**Issue by Lujade** [qpython-android/qpython.org#138]
Trying the add pandas to libraries. When pressing the libraries button I get the following error.
502 Bad Gateway

nginx/1.1.19

**Comment by edgardojs** [comment]
Same w me tried deleting and installing but same

**Comment by victorjabur** [comment]
Same error here. I need to install some libraries to run my scripts. Have we another alternative ?

**Comment by ctmalan** [comment]
Qpython.org wiki also returns 502

**Comment by astearon** [comment]
Same 502 libraries error for me too.

**Comment by thespacious** [comment]
Same issue, any word from dev team?

**Comment by riverfor** [comment]
New versions had fixed this.
