### ISSUE TITLE
Numpy requires python 3.4 or higher

### ISSUE THREAD

**Issue by matthijscox** [qpython-android/qpython.org#156]
Hi I was trying to install numpy via pip (i did not find it in the "library manager" menu, which was the recommended method apparently), but python 3.4 is required while qpython3 runs on 3.2.2.

Is there any way to circumvent this issue? 

-->pip install numpy
Downloading/unpacking numpy
  
  Running setup.py egg_info for package numpy
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/storage/emulated/0/qpython/cache/pip-build/numpy/setup.py", line 34, in <module>
        raise RuntimeError("Python version 2.7 or >= 3.4 required.")
    RuntimeError: Python version 2.7 or >= 3.4 required.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/storage/emulated/0/qpython/cache/pip-build/numpy/setup.py", line 34, in <module>

    raise RuntimeError("Python version 2.7 or >= 3.4 required.")

RuntimeError: Python version 2.7 or >= 3.4 required.

----------------------------------------

**Comment by ovalent** [comment]
Same issue here with qpyhton3. Any plan to upgrade python core to 3.4  or higher?
Or maybe is there any specific version of numpy that could work with python 3.2.2 (e.g.: "-->pip install numpy==x.x.x"?

**Comment by riverfor** [comment]
Only qpython support numpy yet, You can install it from QPYPI by installing the numpy-qpython.

Because of lacking the cross compile toolchain on android, pip couldn't install the library which needs compiling.
