### ISSUE TITLE
Install Error with paho-mqtt Package using PIP

### ISSUE THREAD

**Issue by falbriard** [qpython-android/qpython.org#16]
Receiving an error: build/lib.linux-arm71-2.7/paho/mqtt/__init__.py; Operation not permitted when executing the install via command: pip install paho-mqtt 

Using paho-mqtt would be a useful package for Android connectivity with Python code.
 
Thanks in advance for your assistance. 
Regards
Claude

**Comment by riverfor** [comment]
New version had fixed this issue, please get it from  http://www.pgyer.com/qpython
