### ISSUE TITLE
Erro ao executar comandos como "if, elif e else" 

### ISSUE THREAD

**Issue by Megarik** [qpython-android/qpython.org#164]
O que está errado nesse código:
dia = int(input("Digite o dia da semana:  "))
if dia == 1:
input('Domingo')

No aplicativo QPython3, não executa e fala que é um erro na linha 3 (linha onde tem o input)

**Comment by riverfor** [comment]
```python
dia = int(input("Digite o dia da semana: "))
if dia == 1:
    input('Domingo')
```
Please ask program issues on https://www.facebook.com/groups/qpython, you can get quick feedback.
