### ISSUE TITLE
Script is throwing an issue

### ISSUE THREAD

**Issue by itsramki** [qpython-android/qpython.org#165]
I am saving below code in a script and trying to execute it

print("How old are you?", end=' ')
age = input()
print("How tall are you?", end=' ')
height = input()
print("How much do you weigh?", end=' ')
weight = input()
print(f"So, you're {age} old, {height} tall and {weight} heavy.")

But it is throwing below error

invalid syntax (and the arrow(^) is pointing at ending quote("))

But the same script is running fine in my laptop

**Comment by riverfor** [comment]
It's python3 syntax. The same script runs well on QPython3, but reports SyntaxError on QPython.
