### ISSUE TITLE
qpython multiprocessing Queue error

### ISSUE THREAD

**Issue by barrelo89** [qpython-android/qpython.org#166]
Hi. 

I am trying to use 'qpython' to do some multiprocessing in the android phone.

However, every time I tried to use Queue in the script, I see the following error message.

File "data/data/org.qpython.qp/files/lib/python2.7/site-packages/muliprocessing-2.6.2-p2.7.egg/multiprocessing/snchroize.py", line 49, in __init__
sl = self._semlock = _mulipocessing.SemLock(kind, value, maxvalue)
OSEror: [Errno 28] Function not implemented

In qpython, I can import multiprocessing and even from mutiprocessing import Queue, but 
whenever I declare Queue(), e.g., out = Queue() in the script, I see the error message above. The code runs perfectly well in the window and ubuntu. 

Could you tell me what I am missing in the script and what is wrong in the code? 

Thanks in advance.

**Comment by JIMhackKING** [comment]
Why I cam't install the multiprocessing

**Comment by riverfor** [comment]
In the newest QPython (version >=1.4), you don't need to install multiprocessing,  you could just import multiprocessing .


The newest QPython is using the Python 2.7.12 .
