### ISSUE TITLE
pymongo qpython

### ISSUE THREAD

**Issue by JIMhackKING** [qpython-android/qpython.org#169]
The phone can't open the mongodb server,so the qpython can't use the pymongo?

**Comment by riverfor** [comment]
Can you install pymongo through pip_client.py ?

Which version qpython are you using ?

**Comment by JIMhackKING** [comment]
1.2.9 of qpython2, 1.0.3 of qpython3, but the qpython3 installed a wrong package, when I import pymongo, it raise a SyntaxError.The qpython2 can't connect to mongo server.


来自 银河系信息系统

-------- 原始邮件 --------
发件人：River <notifications@github.com>
时间：周二 7月25日 09:52
收件人："qpython-android/qpython.org" <qpython.org@noreply.github.com>
抄送：Wu Jianmin <a601767890@sina.com>,Author <author@noreply.github.com>
主题：Re: [qpython-android/qpython.org] pymongo qpython (#169)

**Comment by riverfor** [comment]
Maybe the old python2.7.2 isn't compatible with the pymongo.
 
Can you install 1.4.1 (which python is 2.7.12) from https://github.com/qpython-android/qpython/releases ?  (Maybe you need to uninstall and reinstall it)

2.0 alpha is OK also.

After then , you can install pymongo through pip_client.

**Comment by JIMhackKING** [comment]
WOW, the 2.0 alpha is so beautiful,but I still don't know how to open the mongo server.Can you tell me the steps to this?Thanks for your help.


来自 银河系信息系统

**Comment by riverfor** [comment]
You could see the Examples in https://pypi.python.org/pypi/pymongo/3.4.0 .
