### ISSUE TITLE
kivy module crash >>import kivy

### ISSUE THREAD

**Issue by prxy15** [qpython-android/qpython.org#175]
hi, can someone help me with this err,? please 🙏
n/qpython-android5.sh && exit           <
Python 2.7.12 (default, Jul 25 2017, 22:12:10)
[GCC 4.9.x 20150123 (prerelease)] on linux4
Type "help", "copyright", "credits" or "license" for more information.
>>> import kivy
Segmentation fault
139|u0_a110@HWCAM-H:/ $

**Comment by riverfor** [comment]
Kivy didn't support QPython's terminal. Please use it with the '#qpy:kivy' in your script's header.
