### ISSUE TITLE
embedding qpython in android studio app

### ISSUE THREAD

**Issue by mehrdadmraad** [qpython-android/qpython.org#176]
Hi,

I'm new to qpython and want to discover if it is possible to install qpython engine on user device while installing the main apk developed by android studio?

I just need to call some python scripts from my Java code (which I'm doing this through SL4A now) and don't want the user install qpython as a separate app before or after the installation of the main apk.

SL4A is old now and I prefer to embed qpython in my android studio app instead and maybe call my python scripts through qpython SL4A Library.

So how qpython can help me in this regard?

Thanx

**Comment by riverfor** [comment]
Please see this project which contains the python interpreter https://github.com/qpython-android/qpython
