### ISSUE TITLE
import error on unicodedata.so

### ISSUE THREAD

**Issue by dmaziuk** [qpython-android/qpython.org#180]
All my scripts fail with
```
import passlib.hash
```
... trace ...
```
ImportError: dlopen failed: cannot locate symbol "PyUnicodeUCS2_FromUnicode" referenced by "/data/data/org.qpython.qpy/files/lib/python2.7/lib-dynload/unicodedata.so"...
```

Just type "import passlib.hash" in the editor and run it.

Currently v.2.0.10, not sure which update broke it as I haven't run these scripts in a while.

**Comment by riverfor** [comment]
Maybe you can solve this issue by reset storage in setting page.

**Comment by dmaziuk** [comment]
Aah, OK, thanks.

Followed by ```pip install passlib```
