### ISSUE TITLE
Webpage bootstrap CSS should be loaded over HTTPS

### ISSUE THREAD

**Issue by cdeil** [qpython-android/qpython.org#206]
When I open https://www.qpython.org/en/guide.html with latest Chrome on macOS, I get an unstyled page because the bootstrap CSS isn't loaded:

> Mixed Content: The page at 'https://www.qpython.org/en/guide.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css'. This request has been blocked; the content must be served over HTTPS.

Load bootstrap CSS via HTTPS ?

**Comment by riverfor** [comment]
Thanks for feedback. It's solved already.
