### ISSUE TITLE
Qpython3 and androidHelper Issues

### ISSUE THREAD

**Issue by tommyready** [qpython-android/qpython.org#208]
Im currently trying to get the location of my device via the androidHelper but I keep getting null pointer exceptions.

Sample Code:
` while True:
        droid.startLocating()
        droid.eventWaitFor('location', int(9000))
        location = droid.readLocation().result
        if len(location) > 0:
            droid.stopLocating()
            return location `

The error also doesnt give a line number.

**Comment by riverfor** [comment]
Can you try whether the camera permission is enabled with system's setting for qpython 3 ?

And the below contains the test script
https://github.com/qpython-android/qpysl4a/issues/1#issuecomment-580122031
