### ISSUE TITLE
take_picture.py doesn't work

### ISSUE THREAD

**Issue by sktrinh12** [qpython-android/qpython.org#209]
Hi, I just installed qpython and tried to run the take_picture.py default script. It doesn't seem to do anything. This is what it shows:

/data/user/0/org.qpython.qpy3/files/bin/qpyton3-android5.sh /storage/emulated/0/qpython/scripts3/take_picture.py && exit 
thon/scripts3/take_picture/py && exit <
#[QPython] Press enter to exit ...

Seems to have cut out some text. I copied verbatim. I am running it on a samsung galaxy s6

I tried the same script on another phone (s3) and it gave same output with an error exception: java.lang.NullPointerException: throw with null exception

That is the only difference, the rest of the text is the same. Is this an actual issue, or  did I do something wrong? 

Thanks,

**Comment by riverfor** [comment]
Can you try whether the camera permission is enabled with system's setting for qpython 3 ?
