### ISSUE TITLE
Can you run python project with numpy, scipy, pandas, sklearn, rpeackdetector on Android environment using QPython?

### ISSUE THREAD

**Issue by karimkhanp** [qpython-android/qpython.org#210]
I have Python project which usage numpy, scipy, pandas, sklearn, rpeackdetector and few more python libraries..

I want to run this project in Android environment as a app

**Comment by riverfor** [comment]
QPython has supported  numpy, scipy, pandas, sklearn already, you can see xxx-aipy packages from QPYPI, that's what you should install.

We will consider rpeackdetector later. A new issue within QPYPI will be created soon.
