### ISSUE TITLE
focus on a Kivy TextInput kills the script

### ISSUE THREAD

**Issue by cjaramilu** [qpython-android/qpython.org#25]
Focusing on the TextInput ends this script on an Android phone.
There is no error message in the Runtime Log.
The error does not occur when the script is run on the PC.
The error occurs after Qpython switched to Kivy 1.8

    from kivy.lang import Builder
    from kivy.base import runTouchApp
    from kivy.uix.boxlayout import BoxLayout
    from kivy.uix.textinput  import TextInput
    from kivy.uix.label        import Label

    Builder.load_string("""
    #:import kivy kivy
    <Home>':
        orientation: "vertical"
        Label:
            text: "testing textinput problem"
        TextInput:
            text: "123"
        Label:
            text: "kivy version %s"  %   kivy.__version__ 
     """)
    class Home (BoxLayout):
        pass
    runTouchApp (Home() )

**Comment by cjaramilu** [comment]
I want this problem to be solved because I had  2 applications using qpython with kivy
that  stopped working when the last qpython version was released on Novermber.
  
How can I contribute?

**Comment by riverfor** [comment]
Would you like to try the newest version ?

http://www.pgyer.com/qpython

**Comment by cjaramilu** [comment]
The bug is gone

Thanks
