### ISSUE TITLE
/system/bin/sh python not found

### ISSUE THREAD

**Issue by yonnig** [qpython-android/qpython.org#29]
Environment : QPython within Android 4.4.2, Samsung Galaxy Tab Note 8.
Problem: trying to run the console script from the quick-start page... it failed with a "/system/bin/sh python not found" error message.

P.S.: I tried to contact QPython team by e-mail (support@qpython.org), but I got a delivery failure.

**Comment by riverfor** [comment]
Hi, I have uploaded a new BETA version into http://www.pgyer.com/qpython

Can you install it and tell me whether the issued fixed on your device ?

If it still fail, please execute the following code in the console

"source /data/data/com.hipipal.qpyplus/files/bin/init.sh && python"

or

"source /data/data/com.hipipal.qpyplus/files/bin/init.sh && python-android5" (for android5 / androidL user)

Thanks.

**Comment by yonnig** [comment]
Works perfectly with that BETA version.
Thanks for the fix.

**Comment by Chamier** [comment]
It's working just great now! Thanks a lot for your effort and time!

Atentamente,
