### ISSUE TITLE
Transformer tablet still won't run

### ISSUE THREAD

**Issue by paradiselost79** [qpython-android/qpython.org#34]
Transformer 103c running android 4.4.2 still will not run. Such a great app really disappointed our school can't use
![screenshot_2014-12-12-15-18-33](https://cloud.githubusercontent.com/assets/10170753/5419623/ef12309e-8212-11e4-9ab2-ac0e7edfc0e1.png)

**Comment by allesmetkaas** [comment]
Just bought one of these myself. The tablet is Intel Atom, and not Arm - QPython has this error, QPython3 console loads, but I see it's built for Arm V7. Is this arch related?

**Comment by riverfor** [comment]
https://github.com/qpython-android/qpython.org/tree/master/bin

There is a apk for x86, can you test it?

**Comment by allesmetkaas** [comment]
riverfor - Works fine

Python 3.2.2 (Default, Dec 16 2014, 12:40:17)
[GCC 4.6 20120106 (prerelease)]) on linux-i686

Of course a python2 would be nice ;)

**Comment by paradiselost79** [comment]
Still not working for me, downloaded and installed both apk's, still same error

**Comment by riverfor** [comment]
Thanks for feedback,

Can you run python commond in the qpython terminal successfully after executing "export LD_LIBRARY_PATH=/vendor/lib:/system/lib:/data/data/com.hipipal.qpyplus/files"  ?

For qpython3, you need to execute "export LD_LIBRARY_PATH=/vendor/lib:/system/lib:/data/data/com.hipipal.qpy3/files".

**Comment by riverfor** [comment]
Did the BETA version http://www.pgyer.com/qpython3 work fine on your device ?

Thanks.

**Comment by paradiselost79** [comment]
getting an 'unable to launch event' error

**Comment by paradiselost79** [comment]
Finally got it running! Does it normally not have auto-formatting? Indents are hard for a novice like my students (since you can't tab, you have to use your indent button). Syntaxing seems ok, just now starting to play with it.

**Comment by riverfor** [comment]
Happy to know that, I will try to improve tab-key support as soon.

On Fri, Mar 6, 2015 at 11:37 PM, paradiselost79 <notifications@github.com>
wrote:

> Closed #34 <https://github.com/qpython-android/qpython.org/issues/34>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qpython-android/qpython.org/issues/34#event-247570285>
> .
>



-- 
river's showtime, river's game

**Comment by paradiselost79** [comment]
When will update happen? I want to send out to students, but not via .apk
