### ISSUE TITLE
Could not load library libpython - Lenovo Yoga Tablet 2

### ISSUE THREAD

**Issue by Brandl** [qpython-android/qpython.org#37]
Both qpython(0.9.4) and qpython3 throw the following exception, when trying to run then hello_world.py example:

![screenshot_2014-12-25-19-45-52-031](https://cloud.githubusercontent.com/assets/3877188/5554740/372ea994-8c71-11e4-96f6-e6b4c2ec60e4.jpeg)
![screenshot_2014-12-25-19-56-13-376](https://cloud.githubusercontent.com/assets/3877188/5554741/43ac9a46-8c71-11e4-9f4b-29dbdae1de74.jpeg)

**Comment by m017893** [comment]
I have the same behavior on a Lenovo S8-50F tablet, android 4.4.2
Regards,

**Comment by riverfor** [comment]
Is it x86 tablet ? can you try the QPython32x86-0.9.3.apk from https://github.com/qpython-android/qpython.org/tree/master/bin ?

**Comment by Brandl** [comment]
The intel atom processor is capable of 64-bit, but I think all Android tablets until 5.0 are running under 32-bit.

Thanks, I will give it a try later today...

**Comment by Brandl** [comment]
@riverfor  No, sorry didn't work either:
![screenshot_2015-01-15-19-00-08-570](https://cloud.githubusercontent.com/assets/3877188/5763223/f9809458-9ce8-11e4-82d1-0b687a96b6d1.jpeg)

**Comment by paradiselost79** [comment]
Any updates on this? This app is great, I so want to use it in my class instead of codingground website which you have to be online to use, and it randomly goes down.

**Comment by riverfor** [comment]
Can you install the newest qpython3 for x86 from google play ?
Or you can install QPython32x86-0.9.4.apk from
https://github.com/qpython-android/qpython.org/tree/master/bin.

If it doesn't work still, Please create a file which contains "echo
$LD_LIBRARY_PATH" and save as env.sh with qpython3's editor, after that,
please run it and capture the screenshot and send to me.

Thanks for helping us,  I am sorry that I don't have so much android
devices for testing : (
.
Best regards.


On Tue, Jan 27, 2015 at 10:27 PM, paradiselost79 <notifications@github.com>
wrote:

> Any updates on this? This app is great, I so want to use it in my class
> instead of codingground website which you have to be online to use, and it
> randomly goes down.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qpython-android/qpython.org/issues/37#issuecomment-71655558>
> .
>



-- 
river's showtime, river's game

**Comment by Brandl** [comment]
Run with the newest Version of QPython 3 from Google Play:
```
/.last_tmp.py").read())' && sh /data/data/com.hipipal.qpy3/files/bin/end.sh && exit       <
CANNOT LINK EXECUTABLE: could not load library "libpython3.2m.so.1.0" needed by "/data/data/com.hipipal.qpy3/files/bin/python"; caused by library "libpython3.2m.so.1.0" not found
1|u0_a109@YT2:/ $ echo $LD_LIBRARY

u0_a109@YT2:/ $ echo $LD_LIBRARY_PATH
/vendor/lib:/system/lib:/system/lib/arm:/system/lib/egl
```

**Comment by riverfor** [comment]
QPython3 failed to set LD_LIBRARY_PATH for your device, you can try set it
manually

export
LD_LIBRARY_PATH=/vendor/lib:/system/lib:/data/data/com.hipipal.qpy3/files

after than, you can try execute python or python-android5 ( for android 5)
in console.

What kind of device are you using ?


Thanks.


On Mon, Feb 9, 2015 at 2:20 AM, Brandl <notifications@github.com> wrote:

> Run with the newest Version of QPython 3 from Google Play:
>
> /.last_tmp.py").read())' && sh /data/data/com.hipipal.qpy3/files/bin/end.sh && exit       <
> CANNOT LINK EXECUTABLE: could not load library "libpython3.2m.so.1.0" needed by "/data/data/com.hipipal.qpy3/files/bin/python"; caused by library "libpython3.2m.so.1.0" not found
> 1|u0_a109@YT2:/ $ echo $LD_LIBRARY
>
> u0_a109@YT2:/ $ echo $LD_LIBRARY_PATH
> /vendor/lib:/system/lib:/system/lib/arm:/system/lib/egl
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qpython-android/qpython.org/issues/37#issuecomment-73423637>
> .
>



-- 
river's showtime, river's game

**Comment by Brandl** [comment]
Yeah it's strange, but after executing your export command, and running 'python', the shell still yields the same error, as above. :/

**Comment by Brandl** [comment]
Also, manually setting it wouldn't solve the initial problem, of running scripts with the tip of a button and having to invoke them explicitly...

**Comment by Brandl** [comment]
I have posted a bounty of 35$ towards this issue getting fixed:
[![Bountysource](https://www.bountysource.com/badge/issue?issue_id=7263345)](https://www.bountysource.com/issues/7263345-could-not-load-library-libpython-lenovo-y. oga-tablet-2)

This app looks really pronising to me and unfortunatly this bug is quite a showstopper...

**Comment by riverfor** [comment]
Hi,  I have uploaded a new BETA version into http://www.pgyer.com/qpython

Can you install it and tell me whether the issued fixed on your device ?

If it still fail, please execute the following code in the console

"source /data/data/com.hipipal.qpyplus/files/bin/init.sh && python"

or

"source /data/data/com.hipipal.qpyplus/files/bin/init.sh && python-android5"  (for android5 / androidL user)


Thanks.

**Comment by Brandl** [comment]
```bash
#.qpyplus/scripts/.last_tmp.py").read())' && sh /data/data/com.hipipal.qpyplus/files/bin/end.sh && exit                                           <
CANNOT LINK EXECUTABLE: could not load library "libpython2.7.so" needed by "/data/data/com.hipipal.qpyplus/files/bin/python"; caused by library "libpython2.7.so" not found
1|u0_a110@YT2:/ $ echo $LD_LIBRARY_PATH
/vendor/lib:/system/lib:/system/lib/arm:/system/lib/egl
u0_a110@YT2:/ $ python
CANNOT LINK EXECUTABLE: could not load library "libpython2.7.so" needed by "/data/data/com.hipipal.qpyplus/files/bin/python"; caused by library "libpython2.7.so" not found
1|u0_a110@YT2:/ $ source /data/data/com.hipipal.qpyplus/files/bin/init.sh && python
Python 2.7.2 (default, Oct 25 2014, 20:52:15)
[GCC 4.9 20140827 (prerelease)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
u0_a110@YT2:/ $ echo $LD_LIBRARY_PATH
/vendor/lib:/system/lib:/system/lib/arm:/system/lib/egl:/data/data/com.hipipal.qpyplus/files/lib/:/data/data/com.hipipal.qpyplus/files/:/data/data/com.hipipal.qpyplus/lib/
u0_a110@YT2:/ $
```

Here is the complete output, didn't work at first, bit the init-script somehow fixed the problem.
(Put the '#' at the beginning to enable syntax highlighting)

**Comment by riverfor** [comment]
Thanks for feedback, I will fix this issue ASAP.

**Comment by riverfor** [comment]
Hi, I have uploaded a new BETA version into http://www.pgyer.com/qpython again.

Can you install it and tell me whether the issued fixed on your device ?

Thanks.

**Comment by Brandl** [comment]
Thank, yes that solved the issue mostly, all examples run with charm. Except the "WebappExample" seems to still be affecte,:
![tmp_4519-screenshot_2015-02-21-00-51-24-124552679559](https://cloud.githubusercontent.com/assets/3877188/6311561/b4737db0-b964-11e4-9681-9095253a69c2.jpeg)

**Comment by riverfor** [comment]
Got it, I will solve this issue as soon.

Thank you.

**Comment by riverfor** [comment]
Hi, Brandl, please get the newest BETA version from http://www.pgyer.com/qpython ,

Does WebappExample work for you  ?

**Comment by Brandl** [comment]
Yes works with charm. :)
Feel free to claim the bounty and close this issue...

**Comment by riverfor** [comment]
Thank you very much for pushing on fixing this issue.
