### ISSUE TITLE
Can't run a local project on Qpython for Android

### ISSUE THREAD

**Issue by David8989** [qpython-android/qpython.org#43]
When i click to run the project i get this message: 

<rojects/net free/main.py"
link_image[1963]: 10764 could not load needed library 'libpython2.7.so' for 'python' (load_library[1105]: Library 'libpython2.7.so' not found)CANNOT LINK EXECUTABLE
sh-4.2$

It happened when i installed a custom rom on my phone. Before the installation, it didn't showed that message! Please help me someone!

**Comment by riverfor** [comment]
Hi,  I have uploaded a new BETA version into http://www.pgyer.com/qpython

Can you install it and tell me whether the issued fixed  on your device ?

Thanks.

**Comment by David8989** [comment]
Hi. thanks, but i got an error message this time too. Read:

 <us/files/bin/end.sh && exit
link_image[1963]:  9488 could not load needed library 'libpython2.7.so' for 'python' (load_library[1105]: Library 'libpython2.7.so' not found)CANNOT LINK EXECUTABLE
sh-4.2$


it looks like a file "libpython2.7.so" is missing. But from where? :/

**Comment by riverfor** [comment]
If it still fail, please execute the following code in the console

"source /data/data/com.hipipal.qpyplus/files/bin/init.sh && python"

or

"source /data/data/com.hipipal.qpyplus/files/bin/init.sh &&
python-android5" (for android5 / androidL user)

Can you run these code tell me whether the python run well ?


Thanks.

On Tue, Feb 17, 2015 at 6:37 AM, David8989 <notifications@github.com> wrote:

> Hi. thanks, but i got an error message this time too. Read:
>
> <us/files/bin/end.sh && exit
> link_image[1963]: 9488 could not load needed library 'libpython2.7.so'
> for 'python' (load_library[1105]: Library 'libpython2.7.so' not
> found)CANNOT LINK EXECUTABLE
> sh-4.2$
>
> it looks like a file "libpython2.7.so" is missing. But from where? :/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qpython-android/qpython.org/issues/43#issuecomment-74583312>
> .
>



-- 
river's showtime, river's game

**Comment by David8989** [comment]
Sorry to keep bothering but i typed the code on the console and got nothing but the repeated code. See:

 Python 2.7.2 (default, Oct 25 2014, 20:52:15)
[GCC 4.9 20140827 (prerelease)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> "source /data/data/com.hipipal.qpyplus/files/bin/init.sh && python"
'source /data/data/com.hipipal.qpyplus/files/bin/init.sh && python'
>>>


I think i done something wrong but i am not a code expert. Do i need to change the "source" on the code or remove the " "?

**Comment by David8989** [comment]
Yeah, and now i see that it is not only that local project, but ANY project shows this error. Including the pre-made projects like Helloworld.

**Comment by riverfor** [comment]
I am trying to solve this issue : )

**Comment by riverfor** [comment]
Hi, I have uploaded a new BETA version into http://www.pgyer.com/qpython again.

Can you install it and tell me whether the issued fixed on your device ?

Thanks.

**Comment by David8989** [comment]
now i got this message:

 <yplus/files/bin/end.sh && exit
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 6, in <module>
ImportError: No module named ServerInfo
sh-4.2$

**Comment by riverfor** [comment]
Is ServerInfo a 3rd library ?


On Fri, Feb 20, 2015 at 9:37 PM, David8989 <notifications@github.com> wrote:

> now i got this message:
>
> Traceback (most recent call last):
> File "", line 1, in
> File "", line 6, in
> ImportError: No module named ServerInfo
> sh-4.2$
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qpython-android/qpython.org/issues/43#issuecomment-75238747>
> .
>



-- 
river's showtime, river's game

**Comment by David8989** [comment]
I don't know much, because it wasn't me who made the project, i just used it... :(

**Comment by David8989** [comment]
i was looking in the projects folder on the project i want to run and i found a file called "ServerInfo.pyo". Is that the 3rd library you are talking about?

**Comment by riverfor** [comment]
Yes, do you have the source file which ends with ".py" Please put it into the project folder and try again.

**Comment by David8989** [comment]
Mi phone soft-bricked, and i flashed the rom again. I installed that last version you sent me and now its working well! Tannks, youre really awesome!

**Comment by riverfor** [comment]
You are welcome.

: )
