### ISSUE TITLE
os.sys.stdout.write writes additional character

### ISSUE THREAD

**Issue by anonymous22** [qpython-android/qpython.org#44]
When I try:
import os
os.sys.stdout.write(string)
in the qpython console, it outputs the string and one additional character, which seems to be the length of the string. Looks like the function is reading beyond the memory region it should be.

**Comment by riverfor** [comment]
I could not repeat this issue in my device,

What string did you use when the error occured ?

Thanks.

**Comment by anonymous22** [comment]
False alarm it seems. The function behaves as it should, but the interactive interpreter prints its return value right after the string. Since the return value of sys.stdout.write is the length of the string, everything is ok.

**Comment by riverfor** [comment]
Thanks.

On Fri, Mar 20, 2015 at 4:49 AM, anonymous22 <notifications@github.com>
wrote:

> Closed #44 <https://github.com/qpython-android/qpython.org/issues/44>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qpython-android/qpython.org/issues/44#event-259837062>
> .
>



-- 
river's showtime, river's game
