### ISSUE TITLE
Wiki not available

### ISSUE THREAD

**Issue by nyleenho** [qpython-android/qpython.org#45]
When I click on 'Programming guide' in page 'http://qpython.com/',
I go to 'http://wiki.qpython.org/doc/program_guide/',
with the error: '502 Bad Gateway , nginx/1.1.19'
Please repair the WiKi, so I can read the documentation.
Thanks in advance!
Guus.

**Comment by riverfor** [comment]
Thanks for feedback, I have fixed it.

**Comment by nyleenho** [comment]
Thanks a lot!

**Comment by riverfor** [comment]
Thank you for reporting this issue.


On Fri, Feb 20, 2015 at 12:05 AM, Guus <notifications@github.com> wrote:

> Thanks a lot!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qpython-android/qpython.org/issues/45#issuecomment-75078524>
> .
>



-- 
river's showtime, river's game
