### ISSUE TITLE
Unable to run Kivy Apps on Qpython 0.9.9

### ISSUE THREAD

**Issue by kevin-wang2** [qpython-android/qpython.org#46]
When i open any Kivy GUI Apps,it comes with a bug report on consle says KetError:'ANDROID_APP_PATH'.And the same with the demo programme.

**Comment by riverfor** [comment]
Are you using the newest 1.0.x version of QPython ?

Please insert #qpy:kivy into the main.py, we make console app as the default, but old kivy project need to do some changes.

**Comment by Fishtang01** [comment]
Hi, I have the same issue.  I am trying to run the basic hello python on my note 5 samsung. qpython3 version 0.9.9.1  thanks

#-*-coding:utf8;-*-
#qpy:3
#qpy:kivy

from kivy.app import App
from kivy.uix.button import Button

class TestApp(App):
    def build(self):
        # display a button with the text : Hello QPython 
        return Button(text='Hello QPython')

TestApp().run()

**Comment by riverfor** [comment]
QPython 1.4.x had fixed this issue.
Please upgrade from https://play.google.com/store/apps/details?id=org.qpython.qpy

**Comment by riverfor** [comment]
QPython3 may not support kivy, it may support TkInter in the future version.
