### ISSUE TITLE
hello!there are some questions

### ISSUE THREAD

**Issue by 892768447** [qpython-android/qpython.org#65]
hello! recently ,I downloaded QPython, but found it links have changed. before is Faccebook. but now is http://weibo.com/qpython

What are your relationship?

piracy？？

**Comment by ZoomQuiet** [comment]
NIL

i guess because author is Chinese
weibo is Chinese facebook ;-)

plus:
- in China
- people can not visit facebook
- because GFW
- so maybe both SNS link all need list

2015-05-21 11:19 GMT+08:00 ヽoo悾絔℅o。 <notifications@github.com>:

> hello! recently ,I downloaded QPython, but found it links have changed.
> before is Faccebook. but now is http://weibo.com/qpython。
>
> What are your relationship?
>
> piracy？？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qpython-android/qpython.org/issues/65>.
>



-- 
Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by 892768447** [comment]
ok.i got it.Because it has always been in English, not Chinese, thought that the author is abroad

**Comment by riverfor** [comment]
Hi,

Thank you for feedback.

Where do you install the QPython ? The Google play's QPython should show
the Facebook link, and the QPython in Chinese app market shows the weibo's
link.


Thanks.


On Thu, May 21, 2015 at 11:32 AM, ヽoo悾絔℅o。 <notifications@github.com> wrote:

> ok.i got it.Because it has always been in English, not Chinese, thought
> that the author is abroad
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qpython-android/qpython.org/issues/65#issuecomment-104113564>
> .
>



-- 
river's showtime, river's game

**Comment by 892768447** [comment]
oh! I got it.
i install in Chinese app.
maybe ,A long time ago,I always thought it's show Facebook link.
now .i got it

Thanks

**Comment by riverfor** [comment]
: )

You are welcome.


On Mon, May 25, 2015 at 2:15 PM, ヽoo悾絔℅o。 <notifications@github.com> wrote:

> oh! I got it.
> i install in Chinese app.
> maybe ,A long time ago,I always thought it's show Facebook link.
> now .i got it
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qpython-android/qpython.org/issues/65#issuecomment-105138344>
> .
>



-- 
river's showtime, river's game
