### ISSUE TITLE
unable to execute arm-linux-androideabi-gcc

### ISSUE THREAD

**Issue by VijayendraGhadge** [qpython-android/qpython.org#66]
warning: no previously-included files matching '*.pyc' found anywhere in distribution
unable to execute arm-linux-androideabi-gcc: No such file or directory
error: Setup script exited with error: command 'arm-linux-androideabi-gcc' failed with exit status 1

I am trying to execute a setup script using QPythons Python interpreter on the adb shell.

And i wish to have all the precompiled libraries of Python to be present as the are there in Linux when we 
./configure 
make 
make install

Please guide me to a way i can achieve this any help is appreciated.

**Comment by riverfor** [comment]
QPython doesn't support install libraries implemented by c/c++ , because
android lacks full compiling toolchain.

We compile qpython libraries in a cross compiling toolchain.

On Fri, May 29, 2015 at 11:05 AM, Vijayendra Ghadge <
notifications@github.com> wrote:

> warning: no previously-included files matching '*.pyc' found anywhere in
> distribution
> unable to execute arm-linux-androideabi-gcc: No such file or directory
> error: Setup script exited with error: command 'arm-linux-androideabi-gcc'
> failed with exit status 1
>
> I am trying to execute a setup script using QPythons Python interpreter on
> the adb shell.
>
> And i wish to have all the precompiled libraries of Python to be present
> as the are there in Linux when we
> ./configure
> make
> make install
>
> Please guide me to a way i can achieve this any help is appreciated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qpython-android/qpython.org/issues/66>.
>



-- 
river's showtime, river's game

**Comment by VijayendraGhadge** [comment]
So is it possible for me to cross compile python as you did for Qpython with the missing *.pyc compiled to run on arm processors.
By *.pyc files i mean those which are generated when we run ./configure , make and make install in linux.

I am following this Danilo's Tech Blog

http://danilogiulianelli.blogspot.com/2012/10/how-to-cross-compile-python-for-android.html

Here is my shell script with modified the ndk path, patch wget and patch flag to -p1 and the PATH="$ANDROID_NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86/bin/ 

ANDROID_NDK=/home/seed/Downloads/android-ndk-r10e
ANDROID_ABI="armeabi-v7a"
ANDROID_NATIVE_API_LEVEL="android-8"
PYTHON_VERSION="2.6.2"

output_dir=$1
mkdir -p $output_dir
cd $output_dir
# get Python source tarball
wget http://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tgz

# create Python Host version 
tar zxvf Python-$PYTHON_VERSION.tgz
mv Python-$PYTHON_VERSION Host-Python-$PYTHON_VERSION-src
cd Host-Python-$PYTHON_VERSION-src 
./configure --prefix=$output_dir/Host-Python-$PYTHON_VERSION
make
make install

cd $output_dir
# create Python Cross-compiled version for Android
tar zxvf Python-$PYTHON_VERSION.tgz
mv Python-$PYTHON_VERSION Android-Python-$PYTHON_VERSION-src
cd Android-Python-$PYTHON_VERSION-src 

# get and apply Python patch
wget -o PythonPatch https://sites.google.com/site/dgtechblogscripts/Python-2.6.2-android.patch
patch -p1 < Python-2.6.2-android.patch
# fix setup.py
mv setup.py setup.py.orig
cat setup.py.orig | awk '{ if (NR==316) {print " " $0} else {print $0}}' > setup.py

MY_HOSTPYTHON=$output_dir/Host-Python-$PYTHON_VERSION/bin/python
MY_HOSTPGEN=$output_dir/Host-Python-$PYTHON_VERSION-src/Parser/pgen

export ANDROID_NDK
export PATH="$ANDROID_NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86/bin/:$ANDROID_NDK:$ANDROID_NDK/tools:/usr/local/bin:/usr/bin:/bin"
export ARCH=$ANDROID_ABI
export CFLAGS="-DANDROID -mandroid -fomit-frame-pointer --sysroot $ANDROID_NDK/platforms/$ANDROID_NATIVE_API_LEVEL/arch-arm"
export CXXFLAGS="$CFLAGS"
export CC="arm-linux-androideabi-gcc $CFLAGS"
export CXX="arm-linux-androideabi-g++ $CXXFLAGS"
export AR="arm-linux-androideabi-ar"
export RANLIB="arm-linux-androideabi-ranlib"
export STRIP="arm-linux-androideabi-strip --strip-unneeded"
export MAKE="make -j4 install HOSTPYTHON=$MY_HOSTPYTHON HOSTPGEN=$MY_HOSTPGEN CROSS_COMPILE=arm-eabi- CROSS_COMPILE_TARGET=yes"

./configure LDFLAGS="-Wl,--allow-shlib-undefined" CFLAGS="-mandroid -fomit-frame-pointer --sysroot $ANDROID_NDK/platforms/$ANDROID_NATIVE_API_LEVEL/arch-arm" HOSTPYTHON=$MY_HOSTPYTHON HOSTPGEN=$MY_HOSTPGEN --host=arm-eabi --build=i686-pc-linux-gnu --enable-shared --prefix="$output_dir/Android-Python-$PYTHON_VERSION"
sed -i "s|^INSTSONAME=\(.*.so\).*|INSTSONAME=\\1|g" Makefile
$MAKE

I dont get the python executable but lead to compilation errors in the config.log file 

I am not successful yet but leading to ton of bugs.

I am just a beginner at ndk developement .

So my real question is how did QPython crosscompile Python for Android but without the *.pyc files which i need for my software.

Please guide me if i am doing something wrong.

**Comment by VijayendraGhadge** [comment]
How can i set the bit PYTHONDONTWRITEBYTECODE = 0 before standard installation of the QPython.
And how can i enable the mode to compile from byte code because it says compile from byte code is disabled in QPython.
