### ISSUE TITLE
warning: build_py: byte-compiling is disabled, skipping.

### ISSUE THREAD

**Issue by VijayendraGhadge** [qpython-android/qpython.org#72]
Is it possible to somehow enable the byte-compiling ?

**Comment by riverfor** [comment]
Turning off byte-compiling can save device space, 

I have turned it off by default in QPython.

**Comment by ssbarnea** [comment]
I asked myself the same question few months ago and still no answer, here is the link http://stackoverflow.com/questions/35984019/how-can-i-avoid-getting-useless-warnings-while-building-my-package-using-setupto

It is really ugly to keep these warning in the CI logs as in time they will grow and people will start ignoring anything that is logged.
