### ISSUE TITLE
switch in layout dont work

### ISSUE THREAD

**Issue by smarthero50** [qpython-android/qpython.org#73]
hi..........please when i use switch in xml layout....make it restart and not working?
and i have another question please
is there anyway way to show layout not full screen? its important hope you help
thank you

**Comment by riverfor** [comment]
Can you post the relative code here ?

**Comment by smarthero50** [comment]
xml="""<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:orientation="vertical" 
    android:background="#00ff00">


    <Switch
        android:id="@+id/txx"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:gravity="center"
        android:textOff="switch"
        android:textOn="show"/>
</LinearLayout>
"""
import android
droid=android.Android()




droid.fullShow(xml)

**Comment by smarthero50** [comment]
xml="""<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:orientation="vertical" 
    android:background="#00ff00">


    <Switch
        android:id="@+id/txx"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:gravity="center"
        android:textOff="switch"
        android:textOn="show"/>
</LinearLayout>"""
import android
droid=android.Android()




droid.fullShow(xml)

**Comment by smarthero50** [comment]
theres </LinearLayout> in the end of layout but but its not showing up......
and thanks

**Comment by smarthero50** [comment]
sorry but i cant show "<linearlayout " dont know whats wrong here
and thanks

**Comment by smarthero50** [comment]
m="""<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent" >
 
    <TextView
        android:id="@+id/textView1"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentTop="true"
        android:layout_centerHorizontal="true"
        android:layout_marginTop="60dp"
        android:textSize="18sp"
        android:textColor="#4169E1"
        android:text="Static Switch" />
 
    <Switch
        android:id="@+id/switch1"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:text="Switch" />
 
</RelativeLayout>"""

import android
droid=android.Android()


droid.fullShow(m)

**Comment by riverfor** [comment]
m="""<?xml version="1.0" encoding="utf-8"?>
xmlns:tools="http://schemas.android.com/tools"
android:layout_width="match_parent"
android:layout_height="match_parent" >

<TextView
    android:id="@+id/textView1"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_alignParentTop="true"
    android:layout_centerHorizontal="true"
    android:layout_marginTop="60dp"
    android:textSize="18sp"
    android:textColor="#4169E1"
    android:text="Static Switch" />

<Switch
    android:id="@+id/switch1"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_centerInParent="true"
    android:text="Switch" />

"""

import androidhelper
droid= androidhelper.Android()

droid.fullShow(m)


Does it work for you ? I use androidhelper instead of android.

On Mon, Jun 8, 2015 at 7:29 PM, smarthero50 <notifications@github.com>
wrote:

> m="""<?xml version="1.0" encoding="utf-8"?>
> xmlns:tools="http://schemas.android.com/tools"
> android:layout_width="match_parent"
> android:layout_height="match_parent" >
>
> <TextView
>     android:id="@+id/textView1"
>     android:layout_width="wrap_content"
>     android:layout_height="wrap_content"
>     android:layout_alignParentTop="true"
>     android:layout_centerHorizontal="true"
>     android:layout_marginTop="60dp"
>     android:textSize="18sp"
>     android:textColor="#4169E1"
>     android:text="Static Switch" />
>
> <Switch
>     android:id="@+id/switch1"
>     android:layout_width="wrap_content"
>     android:layout_height="wrap_content"
>     android:layout_centerInParent="true"
>     android:text="Switch" />
>
> """
>
> import android
> droid=android.Android()
>
> droid.fullShow(m)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qpython-android/qpython.org/issues/73#issuecomment-109957185>
> .
>



-- 
river's showtime, river's game

**Comment by smarthero50** [comment]
still not working .......anyway thanks for answer
