### ISSUE TITLE
Qpython &Qpython 3 automatically close on script and editor open

### ISSUE THREAD

**Issue by webwraith** [qpython-android/qpython.org#76]
Sony Xperia L, both programs from the app store were tried, and in each the app closes about a second after either the script or editor screens are accessed. I am not seeing any error or log file being created, either

**Comment by riverfor** [comment]
Can you paste the /sdcard/qpy3_last_err.log or /sdcard/qpyplus_last_err.log here ?

Thanks.

**Comment by webwraith** [comment]
I'd love to, but they aren't being created. I've checked all through my sd card, and the files don't exist.

**Comment by webwraith** [comment]
Sorry, I forgot to mention that it's shutting down when I access the "About" menu as well

**Comment by riverfor** [comment]
If you were using QPython | QPython3 | QEditor ... on android 5.x ( Lollipop ) or above, please DISABLE the following setting in android's developer option.

"Don't keep activities" - 
'Destroy every activity as soon as the user leaves it'

Enabling this option may cause Q-Apps close automatically sometimes.

Thanks to Joe, DF7TH who patiently tested QPython and found this cause.

Detail: https://www.facebook.com/photo.php?fbid=715340798600708

**Comment by StevanWhite** [comment]
On my phone, running Android 4.4.2, I found no developer option "Destroy every activity...", but the option "Don't keep activities" triggered the failure.

**Comment by riverfor** [comment]
Were you using the newest version 1.2.2 ?
