### ISSUE TITLE
Trying to install numpy with Qpython

### ISSUE THREAD

**Issue by Lanceliogs** [qpython-android/qpython.org#98]
Hello there!

I'm trying to install numpy with QPypi but it failed every time I tried. I got this in the console:

----------

/data/data/com.hipipal.qpyplus/files/bin/qpython.sh  /data/data/com.hipipal.qpyplus/files/bin/pip  install  numpy  -i  http://pip:qpython@pypi.qpython.com:11000/simple  && exit
com:11000/simple  && exit              <
Downloading/unpacking numpy
  Running setup.py egg_info for package numpy
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/storage/emulated/0/com.hipipal.qpyplus/cache/build/numpy/setup.py", line 18, in <module>
        DOCLINES = __doc__.split("\n")
    AttributeError: 'NoneType' object has no attribute 'split'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/storage/emulated/0/com.hipipal.qpyplus/cache/build/numpy/setup.py", line 18, in <module>

    DOCLINES = __doc__.split("\n")

AttributeError: 'NoneType' object has no attribute 'split'

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in /sdcard/com.hipipal.qpyplus/.pip/pip.log
1|u0_a244@E2003:/ $

---------

Maybe some of you did encounter the same issue and found a solution! I tried to install with pip too and got the same error message.

Have a great day!

Lanceliogs

**Comment by bjmgeek** [comment]
I'm experiencing the same issue. This occurs whether I try to install numpy from QPypi or the included pip console program.

**Comment by davedavemckay** [comment]
I had exactly the same issue. I then tried installing the other packages listed under libraries, Qpypi - Androidhelper, multiprocessing, plyer - these installed fine. Then tried numpy again and it worked. Perhaps one of the others (maybe plyer from the description) sorted out a dependency?

**Comment by davedavemckay** [comment]
It seems the above wasn't successful. Qpypi reports numpy was installed, but it can't then be imported.

/data/user/0/com.hipipal.qpyplus/files/bin/qpython-android5.sh "/storage/emulated/0/com.hipipal.qpyplus/scripts/helloworld.py" && exit
cripts/helloworld.py" && exit            <
Traceback (most recent call last):
  File "/storage/emulated/0/com.hipipal.qpyplus/scripts/helloworld.py", line 17, in <module>
    import numpy
  File "/data/user/0/com.hipipal.qpyplus/files/lib/python2.7/site-packages/numpy-1.3-py2.7.egg/numpy/__init__.py", line 130, in <module>
    import add_newdocs
  File "/data/user/0/com.hipipal.qpyplus/files/lib/python2.7/site-packages/numpy-1.3-py2.7.egg/numpy/add_newdocs.py", line 9, in <module>
    from lib import add_newdoc
ImportError: No module named lib
1|u0_a183@hammerhead:/ $

**Comment by bjmgeek** [comment]
I was able to solve it by going to "Libraries manage" under the menu for
qpython and tapping on numpy from there. Installation with pip or QPypi
still fails, but import numpy works.

**Comment by davedavemckay** [comment]
Great, thanks! That worked for me too. Had to uninstall numpy then installed it through the 'Libraries manage' menu NOT the Libraries list you get too by hitting the icon.
